/**
 * Full agent catalog — every MAS agent from the launch plan.
 * enabled defaults false; routes are capability→provider hints (env can override).
 * Never replaces Cloudinary / Groq / existing listing vision primaries.
 */
import { MAS_TASKS, MAS_PHASE } from "./tasks.js";

/** @typedef {{ id: string, division: number, phase: number, task: string, models: string[], risk: 'zero'|'low'|'medium'|'high', description: string }} MasAgent */

/** @type {MasAgent[]} */
export const MAS_AGENT_CATALOG = [
  // —— Division 1 Security ——
  {
    id: "jailbreak-detect",
    division: 1,
    phase: 1,
    task: MAS_TASKS.JAILBREAK_DETECT,
    models: ["nemoguard-jailbreak-detect"],
    risk: "zero",
    description: "Inspect inbound text for prompt/SQL injection before processing",
  },
  {
    id: "topic-control",
    division: 1,
    phase: 1,
    task: MAS_TASKS.TOPIC_GUARD,
    models: ["llama-3.1-nemoguard-8b-topic-control"],
    risk: "zero",
    description: "Keep chats scoped to Sokoni platform tasks",
  },
  {
    id: "content-safety-text",
    division: 1,
    phase: 1,
    task: MAS_TASKS.CONTENT_SAFETY_TEXT,
    models: ["nemotron-3.5-content-safety", "llama-3.1-nemoguard-8b-content-safety"],
    risk: "zero",
    description: "Scan listings, reviews, messages for toxic/scam/illegal content",
  },
  {
    id: "multimodal-safety",
    division: 1,
    phase: 1,
    task: MAS_TASKS.CONTENT_SAFETY_MULTIMODAL,
    models: ["llama-guard-4-12b"],
    risk: "zero",
    description: "Image+text safety for catalog and chat uploads",
  },
  {
    id: "synthetic-video-detector",
    division: 1,
    phase: 1,
    task: MAS_TASKS.SYNTHETIC_VIDEO_DETECT,
    models: ["synthetic-video-detector"],
    risk: "zero",
    description: "Detect deepfake/manipulated dispute videos (shadow → ops)",
  },

  // —— Division 2 Logistics (stubs) ——
  {
    id: "fleet-cuopt",
    division: 2,
    phase: 4,
    task: MAS_TASKS.FLEET_ROUTE_OPT,
    models: ["cuopt"],
    risk: "high",
    description: "VRP route optimization — stub until fleet GPS ready",
  },
  {
    id: "route-perception",
    division: 2,
    phase: 4,
    task: MAS_TASKS.ROUTE_PERCEPTION,
    models: ["streampetr", "sparsedrive"],
    risk: "high",
    description: "Rider telemetry path perception — stub",
  },
  {
    id: "spatial-bev",
    division: 2,
    phase: 4,
    task: MAS_TASKS.SPATIAL_BEV_MAP,
    models: ["bevformer"],
    risk: "high",
    description: "Bird's-eye pickup/drop layouts — stub",
  },

  // —— Division 3 OCR ——
  {
    id: "receipt-ocr",
    division: 3,
    phase: 1,
    task: MAS_TASKS.RECEIPT_OCR,
    models: ["nemotron-ocr-v2", "nemoretriever-ocr"],
    risk: "zero",
    description: "Receipt / invoice / stock manifest OCR",
  },
  {
    id: "document-parse",
    division: 3,
    phase: 1,
    task: MAS_TASKS.DOCUMENT_PARSE,
    models: ["nemotron-ocr-v1", "paddleocr"],
    risk: "zero",
    description: "Unstructured inventory log → text/tables",
  },
  {
    id: "table-extract",
    division: 3,
    phase: 1,
    task: MAS_TASKS.TABLE_EXTRACT,
    models: ["nemotron-table-structure-v1"],
    risk: "zero",
    description: "Sizing charts / bulk price grids from images",
  },
  {
    id: "page-elements",
    division: 3,
    phase: 1,
    task: MAS_TASKS.PAGE_ELEMENTS,
    models: ["nemotron-page-elements-v3"],
    risk: "zero",
    description: "KYC permit headers/signatures/stamps",
  },
  {
    id: "graphic-isolate",
    division: 3,
    phase: 2,
    task: MAS_TASKS.GRAPHIC_ISOLATE,
    models: ["nemotron-graphic-elements-v1"],
    risk: "low",
    description: "Isolate logos/watermarks from product photos",
  },
  {
    id: "visual-metadata",
    division: 3,
    phase: 1,
    task: MAS_TASKS.VISUAL_METADATA,
    models: ["nemotron-parse"],
    risk: "zero",
    description: "Pull brand/serial/dimension tags from images",
  },

  // —— Division 4 Search ——
  {
    id: "text-embed",
    division: 4,
    phase: 1,
    task: MAS_TASKS.TEXT_EMBED,
    models: ["nemotron-3-embed-1b"],
    risk: "zero",
    description: "Semantic text embeddings for catalog RAG",
  },
  {
    id: "visual-embed",
    division: 4,
    phase: 1,
    task: MAS_TASKS.VISUAL_EMBED,
    models: ["llama-nemotron-embed-vl-1b-v2"],
    risk: "zero",
    description: "Search-by-photo embeddings",
  },
  {
    id: "search-rerank",
    division: 4,
    phase: 1,
    task: MAS_TASKS.SEARCH_RERANK,
    models: ["llama-nemotron-rerank-vl-1b-v2"],
    risk: "zero",
    description: "Rerank text/image search candidates",
  },

  // —— Division 5 Media (never before Cloudinary/HeyGen/Remotion) ——
  {
    id: "studio-flux",
    division: 5,
    phase: 2,
    task: MAS_TASKS.IMAGE_GENERATE,
    models: ["FLUX.1-dev", "FLUX.1-schnell", "stable-diffusion-3.5-large"],
    risk: "low",
    description: "Backdrop / banner generation — assist only",
  },
  {
    id: "image-edit-fast",
    division: 5,
    phase: 2,
    task: MAS_TASKS.IMAGE_EDIT_FAST,
    models: ["flux.2-klein-4b", "FLUX.1-Kontext-dev"],
    risk: "low",
    description: "Fast edit after primary studio path",
  },
  {
    id: "image-text-edit",
    division: 5,
    phase: 2,
    task: MAS_TASKS.IMAGE_TEXT_EDIT,
    models: ["qwen-image", "qwen-image-edit"],
    risk: "low",
    description: "EN/SW text-in-image edit",
  },
  {
    id: "pcb-inspect",
    division: 5,
    phase: 2,
    task: MAS_TASKS.PCB_INSPECT,
    models: ["qwen-image-edit-nvpcb-ovsl2sl"],
    risk: "low",
    description: "Electronics / PCB listing QA",
  },
  {
    id: "video-super-res",
    division: 5,
    phase: 2,
    task: MAS_TASKS.VIDEO_SUPER_RES,
    models: ["video-super-resolution"],
    risk: "low",
    description: "Upscale seller video AFTER primary clip stack fails or as optional enhance",
  },
  {
    id: "video-relight",
    division: 5,
    phase: 2,
    task: MAS_TASKS.VIDEO_RELIGHT,
    models: ["relighting"],
    risk: "low",
    description: "Relight dark listing video — never replaces Cloudinary",
  },
  {
    id: "product-3d",
    division: 5,
    phase: 2,
    task: MAS_TASKS.PRODUCT_3D,
    models: ["TRELLIS"],
    risk: "low",
    description: "2D→3D product model — async only",
  },
  {
    id: "video-motion-sim",
    division: 5,
    phase: 2,
    task: MAS_TASKS.VIDEO_MOTION_SIM,
    models: ["cosmos-transfer2.5-2b", "cosmos-transfer1-7b"],
    risk: "low",
    description: "Physics-aware motion preview from stills",
  },
  {
    id: "video-clip-last-resort",
    division: 5,
    phase: 2,
    task: MAS_TASKS.VIDEO_CLIP_LAST_RESORT,
    models: ["video-super-resolution", "cosmos-transfer2.5-2b"],
    risk: "low",
    description: "Only after Cloudinary Ken Burns AND HeyGen AND Remotion all fail",
  },

  // —— Division 6 Voice ——
  {
    id: "stt-multilingual",
    division: 6,
    phase: 3,
    task: MAS_TASKS.STT_MULTILINGUAL,
    models: ["parakeet-1.1b-rnnt-multilingual-asr", "canary-1b-asr"],
    risk: "medium",
    description: "Multilingual WhatsApp voice-note STT fallback",
  },
  {
    id: "stt-english-fast",
    division: 6,
    phase: 3,
    task: MAS_TASKS.STT_ENGLISH_FAST,
    models: ["parakeet-tdt-0.6b-v2", "parakeet-ctc-1.1b-asr", "whisper-large-v3"],
    risk: "medium",
    description: "Fast English STT fallback",
  },
  {
    id: "audio-denoise",
    division: 6,
    phase: 3,
    task: MAS_TASKS.AUDIO_DENOISE,
    models: ["background-noise-removal", "studio-voice"],
    risk: "medium",
    description: "Denoise rider/seller voice notes before STT",
  },
  {
    id: "tts-expressive",
    division: 6,
    phase: 3,
    task: MAS_TASKS.TTS_EXPRESSIVE,
    models: ["chatterbox-multilingual-tts", "magpie-tts-multilingual"],
    risk: "medium",
    description: "TTS order updates — flag off by default",
  },
  {
    id: "tts-voice-clone",
    division: 6,
    phase: 3,
    task: MAS_TASKS.TTS_VOICE_CLONE,
    models: ["magpie-tts-zeroshot"],
    risk: "medium",
    description: "Merchant voice clone — flag off",
  },
  {
    id: "voice-assistant",
    division: 6,
    phase: 3,
    task: MAS_TASKS.VOICE_ASSISTANT,
    models: ["nemotron-voicechat", "nemotron-asr-streaming"],
    risk: "medium",
    description: "Streaming voice assistant — flag off",
  },
  {
    id: "translate",
    division: 6,
    phase: 3,
    task: MAS_TASKS.TRANSLATE,
    models: ["riva-translate-4b-instruct-v2", "megatron-1b-nmt"],
    risk: "medium",
    description: "Live chat translation assist",
  },
  {
    id: "video-lipsync",
    division: 6,
    phase: 2,
    task: MAS_TASKS.VIDEO_LIPSYNC,
    models: ["LipSync"],
    risk: "low",
    description: "Dub lip-sync AFTER primary video exists — never replaces Cloudinary",
  },
  {
    id: "video-speaker-track",
    division: 6,
    phase: 2,
    task: MAS_TASKS.VIDEO_SPEAKER_TRACK,
    models: ["active-speaker-detection", "eyecontact"],
    risk: "low",
    description: "Speaker / gaze tracking on promo videos",
  },

  // —— Division 7 Reasoning ——
  {
    id: "orchestrator-ultra",
    division: 7,
    phase: 4,
    task: MAS_TASKS.ORCHESTRATOR,
    models: ["nemotron-3-ultra-550b-a55b"],
    risk: "high",
    description: "Master router — shadow only; live chat stays Groq/OpenRouter",
  },
  {
    id: "fast-chat",
    division: 7,
    phase: 3,
    task: MAS_TASKS.FAST_CHAT,
    models: ["deepseek-v4-flash-0731", "diffusiongemma-26b-a4b-it"],
    risk: "medium",
    description: "Chat failover if Groq+OpenRouter both fail",
  },
  {
    id: "fast-task",
    division: 7,
    phase: 3,
    task: MAS_TASKS.FAST_TASK,
    models: ["nemotron-3.5-lightning-30b-a3b", "nemotron-3-nano-30b-a3b"],
    risk: "medium",
    description: "Micro-task assist — never writes escrow/custody alone",
  },
  {
    id: "code-maintainer",
    division: 7,
    phase: 4,
    task: MAS_TASKS.CODE_MAINTAINER,
    models: ["deepseek-v4-pro-0813", "gemma-4-31b-it", "mistral-nemotron", "laguna-xs-2.1"],
    risk: "high",
    description: "Internal tooling only — no prod DB write access",
  },
  {
    id: "reasoning-dispute",
    division: 7,
    phase: 4,
    task: MAS_TASKS.REASONING_DISPUTE,
    models: ["gpt-oss-120b", "gpt-oss-20b"],
    risk: "high",
    description: "Dispute reasoning shadow alongside human ops",
  },

  // —— Division 8 Multimodal ——
  {
    id: "omni-understand",
    division: 8,
    phase: 2,
    task: MAS_TASKS.OMNI_UNDERSTAND,
    models: ["nemotron-3-nano-omni-30b-a3b-reasoning", "muse-glimmer-30b"],
    risk: "low",
    description: "Mixed text/image/voice understanding fallback",
  },
  {
    id: "physical-reason",
    division: 8,
    phase: 4,
    task: MAS_TASKS.PHYSICAL_REASON,
    models: ["cosmos3-nano-reasoner", "cosmos-reason2-8b", "cosmos3-nano"],
    risk: "high",
    description: "Dispute damage video physics — shadow / ops assist",
  },
  {
    id: "fast-vision",
    division: 8,
    phase: 2,
    task: MAS_TASKS.FAST_VISION,
    models: [
      "kimi-k3",
      "minimax-m3",
      "paligemma",
      "llama-3.2-90b-vision-instruct",
      "llama-3.2-11b-vision-instruct",
    ],
    risk: "low",
    description: "Fast listing vision alternate after OpenRouter/NVIDIA/Gemini primary chain",
  },
];

export function agentsForTask(task) {
  return MAS_AGENT_CATALOG.filter((a) => a.task === task);
}

export function catalogSummary() {
  const byDivision = {};
  for (const a of MAS_AGENT_CATALOG) {
    byDivision[a.division] = (byDivision[a.division] || 0) + 1;
  }
  return {
    totalAgents: MAS_AGENT_CATALOG.length,
    byDivision,
    phases: MAS_PHASE,
    note: "Catalog registers agents; live execution requires MAS flags + provider keys. Primaries unchanged.",
  };
}
